payment_transaction.rb: process with pid 5749 started.
payment_transaction.rb: process with pid 2410 started.
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:287:in `query': Mysql2::Error: Lost connection to MySQL server during query: SELECT `payment_transactions`.* FROM `payment_transactions`  WHERE `payment_transactions`.`aasm_state` IN ('unconfirm', 'confirming') (ActiveRecord::StatementInvalid)
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:287:in `block in execute'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:435:in `block in log'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.0.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:430:in `log'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:287:in `execute'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/mysql2_adapter.rb:222:in `execute'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/mysql2_adapter.rb:226:in `exec_query'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/mysql2_adapter.rb:235:in `select'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:24:in `select_all'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/query_cache.rb:63:in `select_all'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.2/lib/active_record/querying.rb:36:in `find_by_sql'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.2/lib/active_record/relation.rb:585:in `exec_queries'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.2/lib/active_record/relation.rb:471:in `load'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.2/lib/active_record/relation.rb:220:in `to_a'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.2/lib/active_record/relation/delegation.rb:12:in `each'
	from /home/deploy/peatio/current/lib/daemons/payment_transaction.rb:24:in `<top (required)>'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
	from lib/daemons/payment_transaction_ctl:6:in `<main>'
payment_transaction.rb: process with pid 2425 started.
/home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:287:in `query': Mysql2::Error: Can't connect to MySQL server on '59.127.216.102' (111 "Connection refused"): SELECT `payment_transactions`.* FROM `payment_transactions`  WHERE `payment_transactions`.`aasm_state` IN ('unconfirm', 'confirming') (ActiveRecord::StatementInvalid)
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:287:in `block in execute'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:435:in `block in log'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.0.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:430:in `log'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:287:in `execute'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/mysql2_adapter.rb:222:in `execute'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/mysql2_adapter.rb:226:in `exec_query'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/mysql2_adapter.rb:235:in `select'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:24:in `select_all'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.2/lib/active_record/connection_adapters/abstract/query_cache.rb:63:in `select_all'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.2/lib/active_record/querying.rb:36:in `find_by_sql'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.2/lib/active_record/relation.rb:585:in `exec_queries'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.2/lib/active_record/relation.rb:471:in `load'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.2/lib/active_record/relation.rb:220:in `to_a'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.0.2/lib/active_record/relation/delegation.rb:12:in `each'
	from /home/deploy/peatio/current/lib/daemons/payment_transaction.rb:24:in `<top (required)>'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
	from /home/deploy/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
	from lib/daemons/payment_transaction_ctl:6:in `<main>'
